"use client";
import { CalendarDays, CreditCard, TrendingDown, TrendingUp } from "lucide-react";
import { DashboardCard } from "@/components/DashboardCard";
import { initialCards, initialEvents, initialMembers, initialTransactions } from "@/lib/mockData";
import { getFinanceSummary, formatCurrency } from "@/lib/finance";
import { FamilyCalendar } from "@/components/FamilyCalendar";
import { FinanceModule } from "@/components/FinanceModule";
import { CalendarItem, Transaction } from "@/lib/types";
import { useState } from "react";
export default function AgendaPage(){const [events,setEvents]=useState<CalendarItem[]>(initialEvents);const [transactions,setTransactions]=useState<Transaction[]>(initialTransactions);const summary=getFinanceSummary(transactions);return <><section className="hero-section"><span className="badge">Família • Agenda • Finanças • IA</span><h1>Bom dia, família Melo.</h1><p className="lead">Resumo inteligente do dia, compromissos, tarefas e contas com lembretes pelo WhatsApp.</p><button className="primary-action">Organizar minha família com IA</button></section><section className="metrics-grid"><DashboardCard title="Próximos eventos" value={String(events.length)} subtitle="Hoje e próximos dias" icon={<CalendarDays/>} tone="blue"/><DashboardCard title="Receitas" value={formatCurrency(summary.income)} subtitle="Total recebido no mês" icon={<TrendingUp/>} tone="green"/><DashboardCard title="Despesas" value={formatCurrency(summary.expenses)} subtitle="Total gasto no mês" icon={<TrendingDown/>} tone="red"/><DashboardCard title="Contas" value={String(summary.pendingBills.length)} subtitle="Com vencimento/alerta" icon={<CreditCard/>} tone="yellow"/></section><div className="content-grid"><FamilyCalendar members={initialMembers} items={events} onAddItem={(item)=>setEvents([item,...events])}/><FinanceModule members={initialMembers} transactions={transactions} cards={initialCards} onAddTransaction={(item)=>setTransactions([item,...transactions])}/></div></>}
